### ISSUE TITLE
Add option to daemonize process

### ISSUE THREAD

**Issue by allinurl** [allinurl/gwsocket#11]

**Comment by jirutka** [comment]
Why? This is responsibility of init/rc system, not the program. This is a bad relict from the age of crappy SysV init.

**Comment by allinurl** [comment]
That's a good point and I'm not sure yet if it's worth it since I want to keep gwsocket as simple as possible. Though, the expectation from this is to have an option for those systems (which I believe are still several) that don't rely on systemd daemons.

**Comment by jirutka** [comment]
This feature is not needed even for SysV init, it'd just simplify the init script. So instead of bloating gwsocket with such functionality, you can provide SysV init script.

BTW I haven't systemd in my mind, basically every init/rc system except plain SysV can daemonize process without boilerplate scripting.

**Comment by allinurl** [comment]
You are right. I definitely don't want to bloat gwsocket by adding features that can be easily solved or have a straight workaround. If this becomes an issue, I'll look into it again.
