### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by jirutka** [allinurl/gwsocket#5]
Please release new version, it’s quite long time and many commits since the last release.

I see that you’ve literally copied gwsocket sources to the goaccess project (very bad practice, it’d be better to use at least git subtree) and it doesn’t look like they are in-sync…?

BTW, thanks for this great utility!

**Comment by allinurl** [comment]
It's certainly been a while since the first release. I'm working to add SSL support which it's been [**asked**](https://github.com/allinurl/goaccess/issues/474) quite a few times. I think that would be a nice cut-off point for the next release. So I definitely plan to push out v0.2 as soon as I have SSL implemented. Stay tuned!

Thanks for the reminder about git subtrees. I'll look into it :)

**Comment by jirutka** [comment]
I’d personally prefer to keep it simple and minimalistic. One can always use nginx or another web proxy for TLS termination. Actually this is exactly my use case.

_Release early, release often._ You can release 0.2 right now and TLS support in 0.3. ;)

BTW I’ve created [Alpine package](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/gwsocket) for gwsocket, that’s why I’m asking for a release.

**Comment by allinurl** [comment]
I agree on keeping it simple, which is the goal of the project :)

Sounds good, I'll release v0.2 today or tomorrow and leave TLS support for v0.3.

Please keep this issue open and I'll post back as soon as this is out. 

Thanks for creating/adding the package to Alpine Linux :+1:

**Comment by jirutka** [comment]
Thanks, but please also create a git tag for v0.2. ;)

**Comment by allinurl** [comment]
[**v0.2**](http://gwsocket.io/) is out! Thanks again!
